### ISSUE TITLE
Latest orb version is not propagated to the circleci.

### ISSUE THREAD

**Issue by jozenstar** [whitesource/whitesource_orb#3]
Currently, the latest version of whitesource at circleci is 20.3.1 (https://circleci.com/developer/orbs/orb/whitesource/whitesource-scan)
It uses `whitesourcesoftware/ua-base:v1` image which is based on Ubuntu 16.04 (EOL was in April 2021) as an executor.
I have a lot of jobs failed because they can't install some packages like `php7.3` from `ppa:ondrej/php` since those package providers no longer provide their packages for the deprecated Ubuntu 16.04.

Master branch of this repo has `circleci/openjdk:8-jdk` used as an image for executor. It's works fine.
The problem is that this version of orb is not deployed on circleci.
Could you please deploy it so we could upgrade and continue using that orb?

Thanks

**Comment by LenaKleyner** [comment]
Hi @jozenstar , thanks for opening this.

You are correct regarding the outdated base image and we are currently working to update it. A new version will be released once this is finalized.
Regarding the master branch of this repo, it was not updated to the latest version (20.3.1) of [whitesource/whitesource-scan](https://circleci.com/developer/orbs/orb/whitesource/whitesource-scan) in CircleCI and reflected version [18.10.2](https://circleci.com/developer/orbs/orb/whitesource/whitesource-scan?version=18.10.2). Thanks for raising this, we have updated the repo in #4.

**Comment by jozenstar** [comment]
Hi @LenaKleyner,
Thanks for your response.

**Comment by CyberLOCK33ID** [comment]
{-o-}[locknode]...locknode^4(o-code-o)#LOCK33Creator>o.LOCK33ID.LOCK33FedoraWorkstation.lock33.tech

**Comment by LenaKleyner** [comment]
@jozenstar ,

We have released version [21.6.3](https://circleci.com/developer/orbs/orb/whitesource/whitesource-scan) which upgraded the executor base image to Ubuntu 18.04.

Please let me know if that resolves your issue.

Thanks,

Lena

**Comment by CyberLOCK33ID** [comment]
o-circleci-o

**Comment by annarozin** [comment]
@jozenstar 
I am closing this as all the items were resolved. Feel free to reopen if you feel otherwise.
Thanks,
Anna

**Comment by annarozin** [comment]
@jozenstar
I am closing this as all the items were resolved. Feel free to reopen if you feel otherwise.
Thanks,
Anna

**Comment by jozenstar** [comment]
@LenaKleyner @annarozin The issue is resolved.
Thanks for the help :)

**Comment by jozenstar** [comment]
@LenaKleyner By the way, there's also a problem with Ubuntu 18.04 libssl. (https://bugs.launchpad.net/ubuntu/+source/nodejs/+bug/1861712)
It's not possible to install both nodejs and php because of that problem.

Is there anything special in `whitesourcesoftware/ua-base:v2` docker image which is a hardcoded executor in the orb?
It would be nice to be able to specify the executor ourselves.

**Comment by LenaKleyner** [comment]
Thanks @jozenstar for the feedback.

The Dockerfile of the image can now be found at [Docker Hub](https://hub.docker.com/r/whitesourcesoftware/ua-base). 
Regarding the suggestion to enable setting the executor image, we will need to check this. Thanks for the suggestion.

Lena
